version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=grupoc
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    command: 'redis-server --appendonly yes --requirepass "redis"'

volumes:
  postgresql:
  redis:
