version: '3'

services:
  postgresql:
    image: postgres
    container_name: postgresql_test
    ports:
      - '5432:5432'
    volumes:
      - postgresql_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=vain
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis
    container_name: redis_test
    ports:
      - '6379:6379'
    volumes:
      - redis_test:/var/lib/redis/data
    command: 'redis-server --appendonly yes'

volumes:
  postgresql_test:
  redis_test:
