name: Development deployment

on:
  workflow_run:
    workflows: ['Semantic release']
    types:
      - completed

jobs:
  deploy:
    name: Deploy to the development environment
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.HOSTINGER_DEVELOPMENT_SSH_KEY }}" > ~/.ssh/id_rsa
          host='${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }}'
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts

      - name: Upload package.json and pnpm-lock.yaml
        run: rsync -r ./package.json ./pnpm-lock.yaml deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }}:~/app/server

      - name: Upload the installed dependencies
        run: rsync -r node_modules deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }}:~/app/server

      - name: Upload the build
        run: rsync -r dist deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }}:~/app/server

      - name: Delete old PM2 processes
        run: ssh deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }} "pm2 delete all"

      - name: Start API
        run: ssh deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }} "cd ~/app/server && pm2 start --name "server:build" dist/shared/infra/http/index.js"

      - name: Start queue
        run: ssh deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }} "cd ~/app/server && pm2 start --name "queue:build" dist/shared/infra/http/queue.js"

      - name: Save PM2 processes
        run: ssh deploy@${{ secrets.HOSTINGER_DEVELOPMENT_IPV4 }} "pm2 save"
